### ISSUE TITLE
foundation-apps-modal.js - a wrong invoke of $templateCache?

### ISSUE THREAD

**Issue by mikhaabel** [mmiii/foundation-apps-modal#1]
@ivnivnch 

Modal pops up once it's called the first time. The second and later times it doesn't work.

There is an issue about _$templateCache_ in the _foundation-apps-modal.js_. On the lines 33-34, there is $templateCache invoke, which results in an object with elements.

`if ($templateCache.get(config.templateUrl)) {
              defer.resolve($templateCache.get(config.templateUrl));`

Later this object is passed to promise but it's not defined, which element of Object it's supposed to use. So _templateUrl_ is not identified which fires an error. 

The suggested fix is pass the only element of the Object:

`if ($templateCache.get(config.templateUrl)) {
              defer.resolve($templateCache.get(config.templateUrl)[1]);`

Sounds like solution?

**Comment by ivnivnch** [comment]
Fixed.
