### ISSUE TITLE
How can I close modal programmatically?

### ISSUE THREAD

**Issue by mikhaabel** [mmiii/foundation-apps-modal#2]
There're directives (zf-close, zf-open, etc) but if I want to close modal from custom controller?

At your provider you use:

```
                       FoundationApi.subscribe(id, function(msg) {
                            switch (msg) {
                                case 'toggle':
                                    if (!scope.active) break;
                                case 'close':
                                case 'hide':
                                    console.log('hide me');
                                    defer.reject(msg);

                                    $timeout(function() {
                                        element.remove();
                                        scope.$destroy();
                                    }, 3000);

                                    FoundationApi.unsubscribe(id);

                                    break;
                            }
                        });
```

But how do I call  `FoundationApi.subscribe(id, 'hide')`, if id of the modal element is random? `var id = FoundationApi.generateUuid();` Any ideas?

PS. I've also made comment in your code fix. Shortly: you better should use [1] element of the object instead of [0].

**Comment by nghilevi** [comment]
Sorry, I just realized that, you can use zfaModalDefer.resolve(); / zfaModalDefer.reject(); to achive that.

Check the README:
https://github.com/ivnivnch/foundation-apps-modal/blob/master/README.md

**Comment by mikhaabel** [comment]
True, thanks.

But what if I want to close modal by hitting "Esc" button? Guess, I should catch the user input in controller (some plugin?) and then trigger either `zfaModalDefer.resolve();` or `zfaModalDefer.reject();`.

**Comment by nghilevi** [comment]
For that, I would suggest using `$document.on('keydown',callback)` for example. And then call ,say, `zfaModalDefer.resolve()` inside the callback. :-)

**Comment by mikhaabel** [comment]
Okay! Let's hope our fixes reviewed soon :+1:

**Comment by vinhnghi223** [comment]
What do you mean by 'our' fixes? Who really fixed what?

**Comment by nghilevi** [comment]
Please close this if the issue has been resolved.
